### ISSUE TITLE
Crash at start under Archlinux

### ISSUE THREAD

**Issue by bda65** [Yashasvi-Sriram/alien-effects-for-13r3#1]
Hi,
I've installed with pip3 install alieneffects-13r3.
python-npyscreen come from AUR (v 4.10.5). Same problem with npyscreen installed with pip3 (same version 4.10.5).

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/npyscreen/apNPSApplicationEvents.py", line 16, in get
    yield self.interal_queue.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/npyscreen/apNPSApplicationEvents.py", line 18, in get
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/alieneffects-13r3", line 18, in <module>
    AlienwareTUI().run()
  File "/usr/lib/python3.7/site-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/usr/lib/python3.7/site-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/usr/lib/python3.7/site-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/usr/lib/python3.7/site-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/usr/lib/python3.7/site-packages/npyscreen/apNPSApplicationManaged.py", line 167, in main
    self._THISFORM.activate()
  File "/usr/lib/python3.7/site-packages/alieneffects/tui.py", line 77, in activate
    self.edit()
  File "/usr/lib/python3.7/site-packages/npyscreen/fm_form_edit_loop.py", line 86, in edit
    self._widgets__[self.editw].edit()
  File "/usr/lib/python3.7/site-packages/npyscreen/wgboxwidget.py", line 150, in edit
    self.entry_widget.edit()
  File "/usr/lib/python3.7/site-packages/npyscreen/wgcombobox.py", line 44, in edit
    super(textbox.Textfield, self).edit()
  File "/usr/lib/python3.7/site-packages/npyscreen/wgwidget.py", line 458, in edit
    self._edit_loop()
  File "/usr/lib/python3.7/site-packages/npyscreen/wgwidget.py", line 474, in _edit_loop
    self.get_and_use_key_press()
  File "/usr/lib/python3.7/site-packages/npyscreen/wgwidget.py", line 575, in get_and_use_key_press
    return self.try_while_waiting()
  File "/usr/lib/python3.7/site-packages/npyscreen/wgwidget.py", line 560, in try_while_waiting
    self.parent.parentApp._internal_while_waiting()
  File "/usr/lib/python3.7/site-packages/npyscreen/apNPSApplicationEvents.py", line 41, in _internal_while_waiting
    self.process_event_queues(max_events_per_queue=self.max_events_per_queue)
  File "/usr/lib/python3.7/site-packages/npyscreen/apNPSApplicationEvents.py", line 51, in process_event_queues
    for event in queue.get(maximum=max_events_per_queue):
RuntimeError: generator raised StopIteration

**Comment by bda65** [comment]
The problem disappeared with the github version of npyscreen.
Sorry ;)
